name: Build, and release on tags

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make env

    - name: Clean data
      run: make clean

    - name: Conflate with OSM data
      run: make conflate

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        make_latest: true
        fail_on_unmatched_files: true
        files: |
          data/changes.geojson
          data/iccu.etag
